### ISSUE TITLE
Protractor-flake no show outputs in console

### ISSUE THREAD

**Issue by murcraft** [NickTomlin/protractor-flake#102]
Hi there!

Thanks for submitting an issue! Please provide the following information:

- Operating system and version
- Node.js version
- Protractor version
- Protractor flake version
- Protractor configuration file
- Output from your test suite

You can collect the first few items easily with the [trouble](https://github.com/NickTomlin/node-trouble) cli `npx @nicktomlin/trouble protractor protractor-flake` (or `npm i -g @nicktomlin/trouble && trouble protractor protractor-flake`)

**Comment by murcraft** [comment]
I have a project with the next parameters:
**Node Version** v8.9.4 (NPM: 5.6.0)
**Operating System**: Windows 10

protractor@5.4.1
protractor-flake@3.4.0

My protractor-flake.file:
_let protractorFlake = require('protractor-flake')
let protractorArgs = []
process.env.maxAttempts = 2

protractorArgs.push('conf.js')
let suiteArg = "--suite=${process.env.suite}"

protractorFlake({
  maxAttempts: process.env.maxAttempts,
  parser: 'standard',
  nodeBin: 'node',
  color: 'magenta',
  protractorArgs: protractorArgs
}, function (status) {
  process.exit(status)
})_

**conf.js file for protractor:**

_const  AllureReporter = require('jasmine-allure-reporter')_

_exports.config = {
  allScriptsTimeout: 11000,
  SELENIUM_PROMISE_MANAGER: false,
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 240000,
  },
  params: {
    waitTimeout: 60000,
  },
  specs: [
    'lib/spec/suite1/*.js',
  ],
  suites: {
    all: 'lib/spec/suite1/test.js',
  },_
 
_baseUrl: process.env.env = 'http://www.google.by',_

  _capabilities: {
    browserName: 'chrome',
    shardTestFiles: process.env.maxinstances > 1,
    maxInstances: process.env.maxinstances,
    chromeOptions: {
      args: [
        'incognito',
        // 'headless',
        // 'disable-gpu',
        'window-size=1920,1080',
        '--disable-infobars',
        '--disable-extensions',
        '--ignore-ssl-errors=true',
        'verbose',
        '--disable-web-security'
      ],
    },
    prefs: {
      download: {
        prompt_for_download: false,
        directory_upgrade: true,
      },
    },
    loggingPrefs: {
      'browser': 'SEVERE',
    },
  },_

  _onPrepare: async () => {
    browser.waitForAngularEnabled(false)
    global.EC = protractor.ExpectedConditions
    global.Logger = require('./lib/helpers/logger')_

   jasmine.getEnv().addReporter(new AllureReporter({
      resultDir: 'allure-results',
    }))

    jasmine.getEnv().addReporter(new function () {
      this.jasmineStarted = function (summary) {
        global.TOTAL = summary.totalSpecsDefined
        global.PASSED = 0
        global.FAILED = 0
        global.SKIPPED = 0
        Logger.info(
          "!----------Tests started. Total tests: ${TOTAL}----------!")
      }
      this.suiteStarted = function (result) {
        Logger.info("--------------------------------------------------")
        Logger.info("Suite starts: ${result.fullName}")
        Logger.info("--------------------------------------------------")
      }
      this.specStarted = function (result) {
        Logger.info("Spec starts: ${result.description}")
      }
      this.specDone = function (result) {
        if (result.status === 'passed') {
          PASSED++
        }
        if (result.status === 'disabled' || result.status === 'pending') {
          SKIPPED++
        }
      }
     this.jasmineDone = function () {
        Logger.info("**************************************************")
        Logger.info("${PASSED + FAILED + SKIPPED} of ${TOTAL} tests done")
        Logger.info("Passed: ${PASSED}")
        Logger.info("Failed: ${FAILED}")
        Logger.info("Skipped: ${SKIPPED}")
        Logger.info("**************************************************")
      }
    })

    jasmine.getEnv().afterEach(async function () {
      await Logger.LogConsoleErrors()
      try {
        await browser.takeScreenshot().then(function (png) {
          allure.createAttachment('Screenshot', function () {
            return new Buffer(png, 'base64')
          }, 'image/png')()
        })
      } catch (e) {
        Logger.error("Screen shot was not taken\n${e}")
      }
    })
    await browser.get('')
  }
}

**Comment by andreybruslik** [comment]
We faced the same problem:

**Node Version** v10.13.0 (NPM: 6.4.1)
**Operating System:** Windows 10

protractor@**5.4.2**
protractor-flake@**3.4.0**

**Comment by jayvdb** [comment]
It seems to be related to something in the v3.4.0 release.  v3.3.0 was working well.

**Comment by jayvdb** [comment]
https://github.com/NickTomlin/protractor-flake/pull/98 seems like the cause.

**Comment by NickTomlin** [comment]
Thanks for finding this. I'll figure out a revert strategy and roll this back in the next few hours for a short term fix, we can then figure a way to incorporate the new functionality with #98 in way that doesn't break things.

**Comment by NickTomlin** [comment]
I've just released `v3.4.1` which removes the feature added in #98. Can someone confirm that this has resolved the issue?

**Comment by murcraft** [comment]
Unfortunatelly, it's still not worked
"protractor": "^5.4.2",
 "protractor-flake": "^3.4.1"

![screen](https://user-images.githubusercontent.com/24752690/51201193-80a35300-190c-11e9-9495-6be972296c97.png)

**Comment by NickTomlin** [comment]
I think the current workaround is to pin to `v3.3.0` I think this is actually broken by the typescript upgrade (that happened between 3.3.0 and 3.4.0 and _not_ the changes in #98. I don't have time to investigate until later today but I'll happily accept a PR in the meantime.

**Comment by murcraft** [comment]
I'm looking forward solving of this problem, thanks!

p.s. I noticed it works only I set "protractor-flake": "3.3.0" certain version, without ^

**Comment by NickTomlin** [comment]
It looks like this was due to some logic in `logger.ts` that did not get moved over in the switch to JS (my fault!). I have a fix that you should be able to use locally by installing from the branch:

```
npm i protractor-flake@NickTomlin/protractor-flake#fix-102
```

@murcraft @jayvdb could one of you test that to verify? If so I can release a new version with that fix in place and re-roll the changes in #98

**Comment by NickTomlin** [comment]
I'm also unpublishing `3.4.0` and `3.4.1` for the time being to prevent others from opting into this breakage with semantic versioning.

**Comment by murcraft** [comment]
Yes, it works!

**Comment by andreybruslik** [comment]
It works! Thanks.

**Comment by NickTomlin** [comment]
@murcraft @andreybruslik 

Just to confirm, are you saying that the branch in `npm i protractor-flake@NickTomlin/protractor-flake#fix-102` you works locally?

**Comment by perchwell-e2e** [comment]
> @murcraft @andreybruslik
> 
> Just to confirm, are you saying that the branch in `npm i protractor-flake@NickTomlin/protractor-flake#fix-102` you works locally?

Yes, my project works with using this branch

**Comment by NickTomlin** [comment]
@perchwell-e2e Great thanks for confirming that!

I'll try to prep a new release this weekend to restore the changes in #98. It looks like there's still some integration test breakage that I need to sort out before that happens.

**Comment by andreybruslik** [comment]
> @murcraft @andreybruslik
> 
> Just to confirm, are you saying that the branch in `npm i protractor-flake@NickTomlin/protractor-flake#fix-102` you works locally?

I'm working with public repo. And now initial issue is not reproducible for me.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this. I'll follow up with re-enabling #98 in the next few weeks when I have time.
